pokedex = {
    '1': {
        'name': 'Bulbasaur',
        'type': ['Grass', 'Poison'],
        'abilities': ['Overgrow', 'Chlorophyll'],
        'hp': 45,
        'attack': 49,
        'defense': 49,
        'sp_atk': 65,
        'sp_def': 65,
        'speed': 45,
        'description': 'A small quadrupedal reptile with a bulb on its back. It lies still in the water, waiting for prey to come close.',
        'image': '🌿'
    },
    '2': {
        'name': 'Ivysaur',
        'type': ['Grass', 'Poison'],
        'abilities': ['Overgrow', 'Chlorophyll'],
        'hp': 60,
        'attack': 62,
        'defense': 63,
        'sp_atk': 80,
        'sp_def': 80,
        'speed': 60,
        'description': 'When the bud on its back starts swelling, it is a sign that it is ready to evolve.',
        'image': '🌱'
    },
    '3': {
        'name': 'Venusaur',
        'type': ['Grass', 'Poison'],
        'abilities': ['Overgrow', 'Chlorophyll'],
        'hp': 80,
        'attack': 82,
        'defense': 83,
        'sp_atk': 100,
        'sp_def': 100,
        'speed': 80,
        'description': 'The flower on its back catches the sun\'s rays and converts them into energy. It blooms when it is receiving plenty of sunlight.',
        'image': '🌺'
    },
    '4': {
        'name': 'Charmander',
        'type': ['Fire'],
        'abilities': ['Blaze', 'Solar Power'],
        'hp': 39,
        'attack': 52,
        'defense': 43,
        'sp_atk': 60,
        'sp_def': 50,
        'speed': 65,
        'description': 'It prefers hot places. It is said that it was born in the caldera of a volcano.',
        'image': '🔥'
    },
    '5': {
        'name': 'Charmeleon',
        'type': ['Fire'],
        'abilities': ['Blaze', 'Solar Power'],
        'hp': 58,
        'attack': 64,
        'defense': 58,
        'sp_atk': 80,
        'sp_def': 65,
        'speed': 80,
        'description': 'When it encounters a foe bigger than itself, it turns aggressive. Once it calms down, it seems to lose its feel for the surroundings.',
        'image': '🔥'
    },
    '6': {
        'name': 'Charizard',
        'type': ['Fire', 'Flying'],
        'abilities': ['Blaze', 'Solar Power'],
        'hp': 78,
        'attack': 84,
        'defense': 78,
        'sp_atk': 109,
        'sp_def': 85,
        'speed': 100,
        'description': 'It breathes fire that is so hot, it melts brick and rock. It is likely to prey upon weakened Pokémon that descend from mountains.',
        'image': '🐉'
    },
    '7': {
        'name': 'Squirtle',
        'type': ['Water'],
        'abilities': ['Torrent', 'Rain Dish'],
        'hp': 44,
        'attack': 48,
        'defense': 65,
        'sp_atk': 50,
        'sp_def': 64,
        'speed': 43,
        'description': 'It closes its shell for protection and is a master at predicting foes\' attacks. A SQUIRTLE\'s shell is harder than diamond.',
        'image': '💧'
    },
    '8': {
        'name': 'Wartortle',
        'type': ['Water'],
        'abilities': ['Torrent', 'Rain Dish'],
        'hp': 59,
        'attack': 63,
        'defense': 80,
        'sp_atk': 65,
        'sp_def': 80,
        'speed': 58,
        'description': 'It is said that this Pokémon was long considered a myth until recently when a small colony was discovered.',
        'image': '💧'
    },
    '9': {
        'name': 'Blastoise',
        'type': ['Water'],
        'abilities': ['Torrent', 'Rain Dish'],
        'hp': 79,
        'attack': 83,
        'defense': 100,
        'sp_atk': 85,
        'sp_def': 105,
        'speed': 78,
        'description': 'It is the final form of SQUIRTLE. The shell is harder than diamond. Water is shot out from inside the shell at high speed.',
        'image': '💧'
    },
'10': {
        'name': 'Caterpie',
        'type': ['Bug'],
        'abilities': ['Shield Dust', 'Run Away'],
        'hp': 45,
        'attack': 30,
        'defense': 35,
        'sp_atk': 20,
        'sp_def': 20,
        'speed': 45,
        'description': 'Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.',
        'image': '🐛'
    },
    '11': {
        'name': 'Metapod',
        'type': ['Bug'],
        'abilities': ['Shed Skin'],
        'hp': 50,
        'attack': 20,
        'defense': 55,
        'sp_atk': 25,
        'sp_def': 25,
        'speed': 30,
        'description': 'It is waiting for the moment to evolve. At this stage, it can only harden, so it remains motionless.',
        'image': '🪵'
    },
    '12': {
        'name': 'Butterfree',
        'type': ['Bug', 'Flying'],
        'abilities': ['Compound Eyes', 'Tinted Lens'],
        'hp': 60,
        'attack': 45,
        'defense': 50,
        'sp_atk': 90,
        'sp_def': 80,
        'speed': 70,
        'description': 'It loves the honey of flowers and can locate flower patches that have even tiny amounts of pollen.',
        'image': '🦋'
    },
    '13': {
        'name': 'Weedle',
        'type': ['Bug', 'Poison'],
        'abilities': ['Shield Dust', 'Run Away'],
        'hp': 40,
        'attack': 35,
        'defense': 30,
        'sp_atk': 20,
        'sp_def': 20,
        'speed': 50,
        'description': 'Beware of the sharp stinger on its head. It hides in grass and bushes where it eats leaves.',
        'image': '🐛'
    },
    '14': {
        'name': 'Kakuna',
        'type': ['Bug', 'Poison'],
        'abilities': ['Shed Skin'],
        'hp': 45,
        'attack': 25,
        'defense': 50,
        'sp_atk': 25,
        'sp_def': 25,
        'speed': 35,
        'description': 'While awaiting evolution, it hides from predators under leaves and in nooks of branches.',
        'image': '🥥'
    },
    '15': {
        'name': 'Beedrill',
        'type': ['Bug', 'Poison'],
        'abilities': ['Swarm', 'Sniper'],
        'hp': 65,
        'attack': 90,
        'defense': 40,
        'sp_atk': 45,
        'sp_def': 80,
        'speed': 75,
        'description': 'It has three poisonous stingers on its forelegs and its tail. They are used to jab its enemy repeatedly.',
        'image': '🐝'
    },
    '16': {
        'name': 'Pidgey',
        'type': ['Normal', 'Flying'],
        'abilities': ['Keen Eye', 'Tangled Feet', 'Big Pecks'],
        'hp': 40,
        'attack': 45,
        'defense': 40,
        'sp_atk': 35,
        'sp_def': 35,
        'speed': 56,
        'description': 'It has an extremely sharp sense of direction. It can unerringly return home, even from far away.',
        'image': '🐦'
    },
    '17': {
        'name': 'Pidgeotto',
        'type': ['Normal', 'Flying'],
        'abilities': ['Keen Eye', 'Tangled Feet', 'Big Pecks'],
        'hp': 63,
        'attack': 60,
        'defense': 55,
        'sp_atk': 50,
        'sp_def': 50,
        'speed': 71,
        'description': 'This Pokémon flies around, patrolling its large territory. If its living space is violated, it shows no mercy.',
        'image': '🦅'
    },
    '18': {
        'name': 'Pidgeot',
        'type': ['Normal', 'Flying'],
        'abilities': ['Keen Eye', 'Tangled Feet', 'Big Pecks'],
        'hp': 83,
        'attack': 80,
        'defense': 75,
        'sp_atk': 70,
        'sp_def': 70,
        'speed': 101,
        'description': 'It spreads its gorgeous wings widely to intimidate enemies. It races through the skies at Mach speed.',
        'image': '🦅'
    },
    '25': {
        'name': 'Pikachu',
        'type': ['Electric'],
        'abilities': ['Static', 'Lightning Rod'],
        'hp': 35,
        'attack': 55,
        'defense': 40,
        'sp_atk': 50,
        'sp_def': 50,
        'speed': 90,
        'description': 'When several of these Pokémon gather, their electricity can build and cause lightning storms. Forests where nests of Pikachu live are dangerous.',
        'image': '⚡'
    },
    '26': {
        'name': 'Raichu',
        'type': ['Electric'],
        'abilities': ['Static', 'Lightning Rod'],
        'hp': 60,
        'attack': 90,
        'defense': 55,
        'sp_atk': 90,
        'sp_def': 80,
        'speed': 110,
        'description': 'When PIKACHU comes into contact with a POKéBALL, it is sometimes struck by a sudden evolution.',
        'image': '⚡'
    },
}